### ISSUE TITLE
Some examples are Latin-1

### ISSUE THREAD

**Issue by Keith-S-Thompson** [cbbrowne/tpp#4]
Several of the *.ttp files under `examples` are encoded in Latin-1 (ISO-8859).

On my system, `tpp debian-packaging.tpp` crashes with:

    /usr/local/bin/tpp:78:in `===': invalid byte sequence in UTF-8 (ArgumentError)
    from /usr/local/bin/tpp:78:in `block in get_pages'
    from /usr/local/bin/tpp:75:in `each_line'
    from /usr/local/bin/tpp:75:in `get_pages'
    from /usr/local/bin/tpp:1389:in `run'
    from /usr/local/bin/tpp:1781:in `<main>'

and leaves the terminal in an inconsistent state.

Two suggestions:

1. Translate the sample `*.tpp` files from Latin-1 to UTF-8 (`iconv -f latin1 -t utf8 ...`).

2. More robust error handling: crashes should shut down ncurses cleanly.

(Possibly this should have been two separate issues.)

**Comment by cbbrowne** [comment]
Arnauld changed things so close is invoked even in case of error.  Commit 084e28488ae71f2eb000de97ec326f877ffc83fe

I have used iconv, as suggested, to translate the relevant ISO-8859 files, in commit 789e68f35926ac9d01d1fc7ccc16eff4b91bd2ee
